### ISSUE TITLE
Send to AutoRepeater from Proxy not work

### ISSUE THREAD

**Issue by computerline1z** [nccgroup/AutoRepeater#38]
I use the newest build version, when select the url on the proxy list, and choose Send To AutoRepeater, AutoRepeater flash, but in the list in AutoRepeater tab doesn't show any request.

**Comment by justinmoore** [comment]
Hey @computerline1z,

It looks like I broke the "Send To AutoRepeater" functionality at some point. I'll look into this right now.

In the interim, AutoRepeater will still work by browsing the site as normal.

Thanks for the bug report,
Justin

**Comment by justinmoore** [comment]
This should be fixed now, I had a boolean comparison that I forgot to remove after I refactored some code. 

Feel free to reopen this issue if it persists. 

Thanks,
Justin

**Comment by computerline1z** [comment]
I try the latest jar, but Send to AutoRepeater still not work, don't see any request at all, does this need any filter or config ?

**Comment by justinmoore** [comment]
Do you have any Replacements set which causes a replacement in the request your sending to AutoRepeater? Requests only appear if there's a replacement that occurs within the request to prevent AutoRepeater from resending the original request.

**Comment by computerline1z** [comment]
I just keep the default value, base replacement and replacement is empty, condition only has 4 value, the first one is checked which I can't change the state or delete it. :(
![image](https://user-images.githubusercontent.com/2786420/43974633-5ccd2132-9d05-11e8-968d-780ab5a6b88f.png)

**Comment by justinmoore** [comment]
AutoRepeater won't do anything unless you specify a "Replacement" or "Base Replacement".

Try setting a Replacement with the following settings as an example:
Type: Remove Header By Name
Match: Cookie
Where: Replace First
(This replacement will remove the "Cookie" header from all requests passing through Burp). 

One other note is you don't need to explicitly send requests to AutoRepeater. By default AutoRepeater will replace and resend requests that pass through or are sent from Burp if there's a replacement in the request.

**Comment by computerline1z** [comment]
It's work now :), thanks you very much for your help !
